// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: TraductorTokens.flex

import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class TraductorTokens {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\4\22\0\1\5\1\0"+
    "\1\6\5\0\2\7\1\10\1\0\1\11\2\0\1\12"+
    "\13\0\1\13\1\0\1\14\3\0\32\15\1\16\1\0"+
    "\1\17\3\0\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\15\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\15"+
    "\1\44\1\15\1\45\1\15\1\46\1\5\1\47\7\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\1\1\2\1\3\1\1\1\4\1\1\1\5\1\6"+
    "\1\7\1\10\1\11\15\7\1\12\1\13\1\1\1\0"+
    "\1\14\6\1\25\7\1\14\5\1\1\0\3\1\1\0"+
    "\10\7\1\15\12\7\1\16\5\7\4\1\1\0\1\17"+
    "\1\20\1\7\1\21\1\22\1\23\1\24\4\7\1\25"+
    "\5\7\1\26\1\27\6\7\2\1\1\16\1\1\1\17"+
    "\1\30\1\7\1\31\4\7\1\32\1\33\1\34\1\7"+
    "\1\35\1\36\1\7\1\37\1\7\1\22\2\1\1\40"+
    "\1\41\4\7\1\42\1\43\1\32\1\1\2\7\1\44"+
    "\1\7\1\43\4\7\1\45\1\46\2\7\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\120\0\120\0\170\0\120\0\240\0\120"+
    "\0\120\0\310\0\120\0\120\0\360\0\u0118\0\u0140\0\u0168"+
    "\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230\0\u0258\0\u0280\0\u02a8"+
    "\0\u02d0\0\120\0\120\0\u02f8\0\u0320\0\50\0\u0348\0\u0370"+
    "\0\u0398\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0"+
    "\0\u04d8\0\u0500\0\u0528\0\u0550\0\u0578\0\u05a0\0\u05c8\0\u05f0"+
    "\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708\0\u0730"+
    "\0\u0758\0\120\0\u0780\0\u07a8\0\u07d0\0\u07f8\0\u0820\0\u0848"+
    "\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\u0960\0\u0988"+
    "\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\310\0\u0a50\0\u0a78\0\u0aa0"+
    "\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90\0\u0bb8\0\310"+
    "\0\u0be0\0\u0c08\0\u0c30\0\u0c58\0\u0c80\0\u0ca8\0\u0cd0\0\u0cf8"+
    "\0\u0d20\0\u0d48\0\50\0\120\0\u0d70\0\310\0\310\0\310"+
    "\0\310\0\u0d98\0\u0dc0\0\u0de8\0\u0e10\0\310\0\u0e38\0\u0e60"+
    "\0\u0e88\0\u0eb0\0\u0ed8\0\310\0\310\0\u0f00\0\u0f28\0\u0f50"+
    "\0\u0f78\0\u0fa0\0\u0fc8\0\u0ff0\0\u1018\0\50\0\u1040\0\120"+
    "\0\310\0\u1068\0\310\0\u1090\0\u10b8\0\u10e0\0\u1108\0\310"+
    "\0\310\0\310\0\u1130\0\310\0\310\0\u1158\0\310\0\u1180"+
    "\0\50\0\u11a8\0\u11d0\0\310\0\310\0\u11f8\0\u1220\0\u1248"+
    "\0\u1270\0\310\0\310\0\50\0\u1298\0\u12c0\0\u12e8\0\310"+
    "\0\u1310\0\50\0\u1338\0\u1360\0\u1388\0\u13b0\0\310\0\310"+
    "\0\u13d8\0\u1400\0\310";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\4\1\3\1\5\1\3"+
    "\1\2\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\3\12\1\25\1\26\3\12\1\27\1\30\3\12\1\31"+
    "\1\32\1\33\1\2\2\0\1\2\2\0\1\2\1\0"+
    "\1\2\1\0\1\2\2\0\1\2\2\0\26\2\52\0"+
    "\1\34\1\35\1\0\1\34\1\35\1\0\1\36\1\0"+
    "\1\34\1\35\1\34\2\35\1\34\2\35\1\34\1\37"+
    "\4\34\1\40\11\34\1\41\4\34\1\42\2\35\1\2"+
    "\2\0\1\2\2\0\1\2\1\0\1\43\1\0\1\44"+
    "\2\0\1\2\2\0\26\2\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\26\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\20\12"+
    "\1\45\5\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\46"+
    "\12\12\1\47\1\12\1\50\10\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\10\12\1\51\4\12\1\52\10\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\1\53\7\12\1\54\4\12"+
    "\1\55\10\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\3\12"+
    "\1\56\22\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\15\12"+
    "\1\57\10\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\20\12"+
    "\1\60\5\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\10\12"+
    "\1\61\15\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\62"+
    "\25\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\15\12\1\63"+
    "\10\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\4\12\1\64"+
    "\21\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\7\12\1\65"+
    "\5\12\1\66\1\12\1\67\2\12\1\70\3\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\4\12\1\71\21\12\2\0"+
    "\1\34\1\35\1\0\1\34\1\35\1\0\1\36\1\0"+
    "\1\34\1\35\1\34\2\35\1\34\2\35\26\34\4\35"+
    "\1\0\2\35\1\0\1\72\1\0\40\35\1\34\1\35"+
    "\1\0\1\34\1\35\1\0\1\36\1\0\1\34\1\35"+
    "\1\34\2\35\1\34\2\35\13\34\1\73\12\34\2\35"+
    "\1\34\1\35\1\0\1\34\1\35\1\0\1\36\1\0"+
    "\1\34\1\35\1\34\2\35\1\34\2\35\20\34\1\74"+
    "\5\34\2\35\1\34\1\35\1\0\1\34\1\35\1\0"+
    "\1\36\1\0\1\34\1\35\1\34\2\35\1\34\2\35"+
    "\4\34\1\75\21\34\2\35\1\34\1\35\1\0\1\34"+
    "\1\35\1\0\1\36\1\0\1\34\1\35\1\34\2\35"+
    "\1\34\2\35\4\34\1\76\21\34\2\35\1\77\2\100"+
    "\1\77\2\100\1\77\1\0\1\101\1\100\1\102\2\100"+
    "\1\77\2\100\26\77\2\100\1\103\1\104\1\0\1\2"+
    "\1\0\1\104\1\103\1\104\1\103\1\104\1\103\2\104"+
    "\1\103\2\104\26\103\2\104\1\12\2\0\1\12\2\0"+
    "\1\12\1\0\1\12\1\0\1\12\2\0\1\12\2\0"+
    "\1\12\1\105\24\12\2\0\1\12\2\0\1\12\2\0"+
    "\1\12\1\0\1\12\1\0\1\12\2\0\1\12\2\0"+
    "\2\12\1\106\23\12\2\0\1\12\2\0\1\12\2\0"+
    "\1\12\1\0\1\12\1\0\1\12\2\0\1\12\2\0"+
    "\23\12\1\107\2\12\2\0\1\12\2\0\1\12\2\0"+
    "\1\12\1\0\1\12\1\0\1\12\2\0\1\12\2\0"+
    "\13\12\1\110\6\12\1\111\3\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\20\12\1\112\5\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\13\12\1\113\12\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\21\12\1\114\4\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\20\12\1\115\5\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\23\12\1\116\2\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\6\12\1\117\17\12\2\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\1\0\1\12\2\0"+
    "\1\12\2\0\14\12\1\120\3\12\1\121\5\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\4\12\1\122\21\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\11\12\1\123\14\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\124\24\12\2\0"+
    "\1\12\2\0\1\12\2\0\1\12\1\0\1\12\1\0"+
    "\1\12\2\0\1\12\2\0\3\12\1\125\10\12\1\126"+
    "\11\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\2\12\1\127"+
    "\1\130\22\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\131"+
    "\25\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\13\12\1\132"+
    "\12\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\23\12\1\133"+
    "\2\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\25\12\1\134"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\13\12\1\135\12\12"+
    "\2\0\1\34\1\35\1\0\1\34\1\35\1\0\1\36"+
    "\1\0\1\34\1\35\1\34\2\35\1\34\2\35\23\34"+
    "\1\136\2\34\2\35\1\34\1\35\1\0\1\34\1\35"+
    "\1\0\1\36\1\0\1\34\1\35\1\34\2\35\1\34"+
    "\2\35\4\34\1\137\21\34\2\35\1\34\1\35\1\0"+
    "\1\34\1\35\1\0\1\36\1\0\1\34\1\35\1\34"+
    "\2\35\1\34\2\35\3\34\1\140\22\34\2\35\1\34"+
    "\1\35\1\0\1\34\1\35\1\0\1\36\1\0\1\34"+
    "\1\35\1\34\2\35\1\34\2\35\13\34\1\141\12\34"+
    "\2\35\1\77\2\100\1\77\2\100\1\77\1\0\1\101"+
    "\1\100\1\2\2\100\1\77\2\100\26\77\11\100\1\0"+
    "\1\142\1\100\1\0\35\100\1\2\2\0\1\2\2\0"+
    "\1\2\1\0\1\2\1\0\1\143\2\0\1\2\2\0"+
    "\26\2\2\0\1\2\2\0\1\2\2\0\1\2\1\0"+
    "\1\43\1\0\1\2\2\0\1\2\2\0\26\2\2\0"+
    "\1\103\1\104\1\144\1\2\1\0\1\104\1\103\1\104"+
    "\1\103\1\104\1\103\2\104\1\103\2\104\26\103\4\104"+
    "\1\144\2\0\43\104\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\15\12"+
    "\1\145\10\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\12\12"+
    "\1\146\13\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\147\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\3\12"+
    "\1\150\22\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\7\12"+
    "\1\151\16\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\2\12"+
    "\1\152\23\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\15\12"+
    "\1\153\10\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\7\12"+
    "\1\154\16\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\155\24\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\156\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\22\12"+
    "\1\157\3\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\24\12"+
    "\1\160\1\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\161\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\15\12"+
    "\1\162\10\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\163\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\164\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\165\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\22\12"+
    "\1\166\3\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\16\12"+
    "\1\167\7\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\10\12"+
    "\1\170\15\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\171"+
    "\25\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\13\12\1\172"+
    "\12\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\13\12\1\173"+
    "\12\12\2\0\1\34\1\35\1\0\1\34\1\35\1\0"+
    "\1\36\1\0\1\34\1\35\1\34\2\35\1\34\2\35"+
    "\4\34\1\174\21\34\2\35\1\34\1\35\1\0\1\34"+
    "\1\35\1\0\1\36\1\0\1\34\1\35\1\34\2\35"+
    "\1\34\2\35\4\34\1\175\21\34\2\35\1\34\1\35"+
    "\1\0\1\34\1\35\1\0\1\176\1\0\1\34\1\35"+
    "\1\34\2\35\1\34\2\35\26\34\2\35\1\34\1\35"+
    "\1\0\1\34\1\35\1\0\1\36\1\0\1\34\1\35"+
    "\1\34\2\35\1\34\2\35\13\34\1\177\12\34\2\35"+
    "\12\0\1\200\35\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\13\12"+
    "\1\201\12\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\13\12"+
    "\1\202\12\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\20\12"+
    "\1\203\5\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\4\12"+
    "\1\204\21\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\13\12"+
    "\1\205\12\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\2\12"+
    "\1\206\23\12\2\0\1\12\2\0\1\12\2\0\1\12"+
    "\1\0\1\12\1\0\1\12\2\0\1\12\2\0\1\207"+
    "\25\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\14\12\1\210"+
    "\11\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\21\12\1\211"+
    "\4\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\13\12\1\212"+
    "\12\12\2\0\1\12\2\0\1\12\2\0\1\12\1\0"+
    "\1\12\1\0\1\12\2\0\1\12\2\0\1\213\25\12"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\4\12\1\214\21\12"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\3\12\1\215\22\12"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\20\12\1\216\5\12"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\4\12\1\217\21\12"+
    "\2\0\1\12\2\0\1\12\2\0\1\12\1\0\1\12"+
    "\1\0\1\12\2\0\1\12\2\0\15\12\1\220\10\12"+
    "\2\0\1\34\1\35\1\0\1\34\1\35\1\0\1\221"+
    "\1\0\1\34\1\35\1\34\2\35\1\34\2\35\26\34"+
    "\2\35\1\34\1\35\1\0\1\34\1\35\1\0\1\36"+
    "\1\0\1\34\1\35\1\34\2\35\1\34\2\35\14\34"+
    "\1\222\11\34\2\35\1\34\1\35\1\0\1\34\1\35"+
    "\1\0\1\36\1\0\1\34\1\35\1\34\2\35\1\34"+
    "\2\35\15\34\1\223\10\34\2\35\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\4\12\1\224\21\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\3\12\1\225\22\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\4\12\1\226\21\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\15\12\1\227\10\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\20\12\1\230\5\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\14\12\1\231\11\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\4\12\1\232\21\12\2\0\1\12\2\0\1\12"+
    "\2\0\1\12\1\0\1\12\1\0\1\12\2\0\1\12"+
    "\2\0\24\12\1\233\1\12\2\0\1\34\1\35\1\0"+
    "\1\34\1\35\1\0\1\234\1\0\1\34\1\35\1\34"+
    "\2\35\1\34\2\35\26\34\2\35\1\34\1\35\1\0"+
    "\1\34\1\35\1\0\1\36\1\0\1\34\1\35\1\34"+
    "\2\35\1\34\2\35\24\34\1\235\1\34\2\35\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\2\12\1\236\23\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\13\12\1\237\12\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\3\12\1\240\22\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\6\12\1\241\17\12\2\0\1\34"+
    "\1\35\1\0\1\34\1\35\1\0\1\242\1\0\1\34"+
    "\1\35\1\34\2\35\1\34\2\35\26\34\2\35\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\10\12\1\243\15\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\15\12\1\244\10\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\13\12\1\245\12\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\20\12\1\246\5\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\20\12\1\247\5\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\4\12\1\250\21\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\2\12\1\251\23\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\13\12\1\252\12\12\2\0\1\12"+
    "\2\0\1\12\2\0\1\12\1\0\1\12\1\0\1\12"+
    "\2\0\1\12\2\0\4\12\1\253\21\12\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5160];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\1\2\11\1\1\1\11\1\1\2\11\1\1\2\11"+
    "\15\1\2\11\1\1\1\0\34\1\1\11\5\1\1\0"+
    "\3\1\1\0\35\1\1\0\1\1\1\11\33\1\1\11"+
    "\53\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TraductorTokens(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("ETIQUETA_VALOR2 => " + yytext());
            }
            // fall through
          case 40: break;
          case 2:
            { 
            }
            // fall through
          case 41: break;
          case 3:
            { System.out.print(yytext());
            }
            // fall through
          case 42: break;
          case 4:
            { System.out.println("COMA => " + yytext());
            }
            // fall through
          case 43: break;
          case 5:
            { System.out.println("PUNTO_COMA => " + yytext());
            }
            // fall through
          case 44: break;
          case 6:
            { System.out.println("IGUAL => " + yytext());
            }
            // fall through
          case 45: break;
          case 7:
            { System.out.println("IDENTIFICADOR => " + yytext());
            }
            // fall through
          case 46: break;
          case 8:
            { System.out.println("CORCHETE_A => " + yytext());
            }
            // fall through
          case 47: break;
          case 9:
            { System.out.println("CORCHETE_C => " + yytext());
            }
            // fall through
          case 48: break;
          case 10:
            { System.out.println("LLAVE_A => " + yytext());
            }
            // fall through
          case 49: break;
          case 11:
            { System.out.println("LLAVE_C => " + yytext());
            }
            // fall through
          case 50: break;
          case 12:
            { System.out.println("ETIQUETA_VALOR => " + yytext());
            }
            // fall through
          case 51: break;
          case 13:
            { System.out.println("DIRECCION => " + yytext());
            }
            // fall through
          case 52: break;
          case 14:
            { System.out.println("C_ROJO => " + yytext());
            }
            // fall through
          case 53: break;
          case 15:
            { System.out.println("COMENTARIO/* => " + yytext());
            }
            // fall through
          case 54: break;
          case 16:
            { System.out.println("COMENTARIO// => " + yytext());
            }
            // fall through
          case 55: break;
          case 17:
            { System.out.println("DIR_BACK => " + yytext());
            }
            // fall through
          case 56: break;
          case 18:
            { System.out.println("C_AZUL => " + yytext());
            }
            // fall through
          case 57: break;
          case 19:
            { System.out.println("FT_BOLD => " + yytext());
            }
            // fall through
          case 58: break;
          case 20:
            { System.out.println("DIR_BOTH => " + yytext());
            }
            // fall through
          case 59: break;
          case 21:
            { System.out.println("ARISTA => " + yytext());
            }
            // fall through
          case 60: break;
          case 22:
            { System.out.println("NODO => " + yytext());
            }
            // fall through
          case 61: break;
          case 23:
            { System.out.println("DIR_NONE => " + yytext());
            }
            // fall through
          case 62: break;
          case 24:
            { System.out.println("ARBOL => " + yytext());
            }
            // fall through
          case 63: break;
          case 25:
            { System.out.println("COLOR => " + yytext());
            }
            // fall through
          case 64: break;
          case 26:
            { System.out.println("C_VERDE => " + yytext());
            }
            // fall through
          case 65: break;
          case 27:
            { System.out.println("HIJOS => " + yytext());
            }
            // fall through
          case 66: break;
          case 28:
            { System.out.println("ETIQUETA => " + yytext());
            }
            // fall through
          case 67: break;
          case 29:
            { System.out.println("SH => " + yytext());
            }
            // fall through
          case 68: break;
          case 30:
            { System.out.println("FT_SOLID => " + yytext());
            }
            // fall through
          case 69: break;
          case 31:
            { System.out.println("FUENTE => " + yytext());
            }
            // fall through
          case 70: break;
          case 32:
            { System.out.println("SH_CIRCULO => " + yytext());
            }
            // fall through
          case 71: break;
          case 33:
            { System.out.println("FT_DASHED => " + yytext());
            }
            // fall through
          case 72: break;
          case 34:
            { System.out.println("SH_CUADRADO => " + yytext());
            }
            // fall through
          case 73: break;
          case 35:
            { System.out.println("C_AMARILLLO => " + yytext());
            }
            // fall through
          case 74: break;
          case 36:
            { System.out.println("DIR_FORWARD => " + yytext());
            }
            // fall through
          case 75: break;
          case 37:
            { System.out.println("COLOR_FUENTE => " + yytext());
            }
            // fall through
          case 76: break;
          case 38:
            { System.out.println("SH_RECTANGULO => " + yytext());
            }
            // fall through
          case 77: break;
          case 39:
            { System.out.println("SH_DOBLECIRCULO => " + yytext());
            }
            // fall through
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java TraductorTokens [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        TraductorTokens scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new TraductorTokens(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
