// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: TraductorTokens.flex

import java_cup.runtime.Symbol;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class TraductorTokens {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\4\22\0\1\1\1\5"+
    "\1\6\7\0\1\7\1\0\1\10\2\0\1\11\12\5"+
    "\1\0\1\12\1\0\1\13\1\0\1\5\1\0\32\14"+
    "\1\15\1\0\1\16\1\0\1\5\1\0\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\14\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\14\1\43\1\14\1\44\1\14"+
    "\1\45\1\0\1\46\7\0\1\3\33\0\1\5\35\0"+
    "\1\5\41\0\1\5\7\0\1\5\3\0\1\5\5\0"+
    "\1\5\6\0\1\5\u012d\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\6\1\7\1\10\15\6\1\11\1\12\1\0\1\13"+
    "\6\0\25\6\10\0\1\14\1\0\10\6\1\15\12\6"+
    "\1\16\5\6\4\0\1\17\1\6\1\20\1\21\1\22"+
    "\1\23\4\6\1\24\5\6\1\25\1\26\6\6\2\0"+
    "\1\27\1\0\1\30\1\6\1\31\4\6\1\32\1\33"+
    "\1\34\1\6\1\35\1\36\1\6\1\37\1\6\1\40"+
    "\2\0\1\41\1\42\4\6\1\43\1\44\1\45\1\0"+
    "\2\6\1\46\1\6\1\47\4\6\1\50\1\51\2\6"+
    "\1\52";

  private static int [] zzUnpackAction() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\47\0\116\0\47\0\165\0\47\0\47"+
    "\0\234\0\47\0\47\0\303\0\352\0\u0111\0\u0138\0\u015f"+
    "\0\u0186\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297"+
    "\0\47\0\47\0\u02be\0\47\0\u02e5\0\u030c\0\u0333\0\u035a"+
    "\0\u0381\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444\0\u046b\0\u0492"+
    "\0\u04b9\0\u04e0\0\u0507\0\u052e\0\u0555\0\u057c\0\u05a3\0\u05ca"+
    "\0\u05f1\0\u0618\0\u063f\0\u0666\0\u068d\0\u06b4\0\u06db\0\u0702"+
    "\0\u0729\0\u0750\0\u0777\0\u079e\0\u07c5\0\u07ec\0\u0813\0\u0813"+
    "\0\u083a\0\u0861\0\u0888\0\u08af\0\u08d6\0\u08fd\0\u0924\0\u094b"+
    "\0\u0972\0\234\0\u0999\0\u09c0\0\u09e7\0\u0a0e\0\u0a35\0\u0a5c"+
    "\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8\0\234\0\u0b1f\0\u0b46\0\u0b6d"+
    "\0\u0b94\0\u0bbb\0\u0be2\0\u0c09\0\u0c30\0\u0c57\0\47\0\u0c7e"+
    "\0\234\0\234\0\234\0\234\0\u0ca5\0\u0ccc\0\u0cf3\0\u0d1a"+
    "\0\234\0\u0d41\0\u0d68\0\u0d8f\0\u0db6\0\u0ddd\0\234\0\234"+
    "\0\u0e04\0\u0e2b\0\u0e52\0\u0e79\0\u0ea0\0\u0ec7\0\u0eee\0\u0f15"+
    "\0\47\0\u0f3c\0\234\0\u0f63\0\234\0\u0f8a\0\u0fb1\0\u0fd8"+
    "\0\u0fff\0\234\0\234\0\234\0\u1026\0\234\0\234\0\u104d"+
    "\0\234\0\u1074\0\47\0\u109b\0\u10c2\0\234\0\234\0\u10e9"+
    "\0\u1110\0\u1137\0\u115e\0\234\0\234\0\47\0\u1185\0\u11ac"+
    "\0\u11d3\0\234\0\u11fa\0\47\0\u1221\0\u1248\0\u126f\0\u1296"+
    "\0\234\0\234\0\u12bd\0\u12e4\0\234";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\2\3\3\1\2\1\4\1\2\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\3\11\1\24\1\25\3\11"+
    "\1\26\1\27\3\11\1\30\1\31\1\32\50\0\2\33"+
    "\1\0\2\33\1\34\5\0\1\33\2\0\1\33\1\35"+
    "\4\33\1\36\11\33\1\37\4\33\1\40\11\0\1\41"+
    "\1\0\1\42\42\0\1\11\6\0\1\11\2\0\26\11"+
    "\7\0\1\11\6\0\1\11\2\0\20\11\1\43\5\11"+
    "\7\0\1\11\6\0\1\11\2\0\1\44\12\11\1\45"+
    "\1\11\1\46\10\11\7\0\1\11\6\0\1\11\2\0"+
    "\10\11\1\47\4\11\1\50\10\11\7\0\1\11\6\0"+
    "\1\11\2\0\1\51\7\11\1\52\4\11\1\53\10\11"+
    "\7\0\1\11\6\0\1\11\2\0\3\11\1\54\22\11"+
    "\7\0\1\11\6\0\1\11\2\0\15\11\1\55\10\11"+
    "\7\0\1\11\6\0\1\11\2\0\20\11\1\56\5\11"+
    "\7\0\1\11\6\0\1\11\2\0\10\11\1\57\15\11"+
    "\7\0\1\11\6\0\1\11\2\0\1\60\25\11\7\0"+
    "\1\11\6\0\1\11\2\0\15\11\1\61\10\11\7\0"+
    "\1\11\6\0\1\11\2\0\4\11\1\62\21\11\7\0"+
    "\1\11\6\0\1\11\2\0\7\11\1\63\5\11\1\64"+
    "\1\11\1\65\2\11\1\66\3\11\7\0\1\11\6\0"+
    "\1\11\2\0\4\11\1\67\21\11\3\0\2\33\1\0"+
    "\2\33\1\34\5\0\1\33\2\0\26\33\3\0\2\33"+
    "\1\0\2\33\1\34\5\0\1\33\2\0\13\33\1\70"+
    "\12\33\3\0\2\33\1\0\2\33\1\34\5\0\1\33"+
    "\2\0\20\33\1\71\5\33\3\0\2\33\1\0\2\33"+
    "\1\34\5\0\1\33\2\0\4\33\1\72\21\33\3\0"+
    "\2\33\1\0\2\33\1\34\5\0\1\33\2\0\4\33"+
    "\1\73\21\33\3\0\2\74\1\0\2\74\1\0\1\75"+
    "\1\0\1\76\2\0\1\74\2\0\26\74\3\0\1\77"+
    "\1\100\1\0\2\77\3\0\1\101\2\0\1\77\2\0"+
    "\26\77\7\0\1\11\6\0\1\11\2\0\1\11\1\102"+
    "\24\11\7\0\1\11\6\0\1\11\2\0\2\11\1\103"+
    "\23\11\7\0\1\11\6\0\1\11\2\0\23\11\1\104"+
    "\2\11\7\0\1\11\6\0\1\11\2\0\13\11\1\105"+
    "\6\11\1\106\3\11\7\0\1\11\6\0\1\11\2\0"+
    "\20\11\1\107\5\11\7\0\1\11\6\0\1\11\2\0"+
    "\13\11\1\110\12\11\7\0\1\11\6\0\1\11\2\0"+
    "\21\11\1\111\4\11\7\0\1\11\6\0\1\11\2\0"+
    "\20\11\1\112\5\11\7\0\1\11\6\0\1\11\2\0"+
    "\23\11\1\113\2\11\7\0\1\11\6\0\1\11\2\0"+
    "\6\11\1\114\17\11\7\0\1\11\6\0\1\11\2\0"+
    "\14\11\1\115\3\11\1\116\5\11\7\0\1\11\6\0"+
    "\1\11\2\0\4\11\1\117\21\11\7\0\1\11\6\0"+
    "\1\11\2\0\11\11\1\120\14\11\7\0\1\11\6\0"+
    "\1\11\2\0\1\11\1\121\24\11\7\0\1\11\6\0"+
    "\1\11\2\0\3\11\1\122\10\11\1\123\11\11\7\0"+
    "\1\11\6\0\1\11\2\0\2\11\1\124\1\125\22\11"+
    "\7\0\1\11\6\0\1\11\2\0\1\126\25\11\7\0"+
    "\1\11\6\0\1\11\2\0\13\11\1\127\12\11\7\0"+
    "\1\11\6\0\1\11\2\0\23\11\1\130\2\11\7\0"+
    "\1\11\6\0\1\11\2\0\25\11\1\131\7\0\1\11"+
    "\6\0\1\11\2\0\13\11\1\132\12\11\3\0\2\33"+
    "\1\0\2\33\1\34\5\0\1\33\2\0\23\33\1\133"+
    "\2\33\3\0\2\33\1\0\2\33\1\34\5\0\1\33"+
    "\2\0\4\33\1\134\21\33\3\0\2\33\1\0\2\33"+
    "\1\34\5\0\1\33\2\0\3\33\1\135\22\33\3\0"+
    "\2\33\1\0\2\33\1\34\5\0\1\33\2\0\13\33"+
    "\1\136\12\33\3\0\2\74\1\0\2\74\1\0\1\75"+
    "\4\0\1\74\2\0\26\74\13\0\1\137\44\0\1\41"+
    "\40\0\1\77\1\100\1\0\2\77\6\0\1\77\2\0"+
    "\26\77\13\0\1\42\42\0\1\11\6\0\1\11\2\0"+
    "\15\11\1\140\10\11\7\0\1\11\6\0\1\11\2\0"+
    "\12\11\1\141\13\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\142\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\3\11\1\143\22\11\7\0\1\11\6\0\1\11\2\0"+
    "\7\11\1\144\16\11\7\0\1\11\6\0\1\11\2\0"+
    "\2\11\1\145\23\11\7\0\1\11\6\0\1\11\2\0"+
    "\15\11\1\146\10\11\7\0\1\11\6\0\1\11\2\0"+
    "\7\11\1\147\16\11\7\0\1\11\6\0\1\11\2\0"+
    "\1\11\1\150\24\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\151\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\22\11\1\152\3\11\7\0\1\11\6\0\1\11\2\0"+
    "\24\11\1\153\1\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\154\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\15\11\1\155\10\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\156\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\157\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\4\11\1\160\21\11\7\0\1\11\6\0\1\11\2\0"+
    "\22\11\1\161\3\11\7\0\1\11\6\0\1\11\2\0"+
    "\16\11\1\162\7\11\7\0\1\11\6\0\1\11\2\0"+
    "\10\11\1\163\15\11\7\0\1\11\6\0\1\11\2\0"+
    "\1\164\25\11\7\0\1\11\6\0\1\11\2\0\13\11"+
    "\1\165\12\11\7\0\1\11\6\0\1\11\2\0\13\11"+
    "\1\166\12\11\3\0\2\33\1\0\2\33\1\34\5\0"+
    "\1\33\2\0\4\33\1\167\21\33\3\0\2\33\1\0"+
    "\2\33\1\34\5\0\1\33\2\0\4\33\1\170\21\33"+
    "\3\0\2\33\1\0\2\33\1\171\5\0\1\33\2\0"+
    "\26\33\3\0\2\33\1\0\2\33\1\34\5\0\1\33"+
    "\2\0\13\33\1\172\12\33\7\0\1\11\6\0\1\11"+
    "\2\0\13\11\1\173\12\11\7\0\1\11\6\0\1\11"+
    "\2\0\13\11\1\174\12\11\7\0\1\11\6\0\1\11"+
    "\2\0\20\11\1\175\5\11\7\0\1\11\6\0\1\11"+
    "\2\0\4\11\1\176\21\11\7\0\1\11\6\0\1\11"+
    "\2\0\13\11\1\177\12\11\7\0\1\11\6\0\1\11"+
    "\2\0\2\11\1\200\23\11\7\0\1\11\6\0\1\11"+
    "\2\0\1\201\25\11\7\0\1\11\6\0\1\11\2\0"+
    "\14\11\1\202\11\11\7\0\1\11\6\0\1\11\2\0"+
    "\21\11\1\203\4\11\7\0\1\11\6\0\1\11\2\0"+
    "\13\11\1\204\12\11\7\0\1\11\6\0\1\11\2\0"+
    "\1\205\25\11\7\0\1\11\6\0\1\11\2\0\4\11"+
    "\1\206\21\11\7\0\1\11\6\0\1\11\2\0\3\11"+
    "\1\207\22\11\7\0\1\11\6\0\1\11\2\0\20\11"+
    "\1\210\5\11\7\0\1\11\6\0\1\11\2\0\4\11"+
    "\1\211\21\11\7\0\1\11\6\0\1\11\2\0\15\11"+
    "\1\212\10\11\3\0\2\33\1\0\2\33\1\213\5\0"+
    "\1\33\2\0\26\33\3\0\2\33\1\0\2\33\1\34"+
    "\5\0\1\33\2\0\14\33\1\214\11\33\3\0\2\33"+
    "\1\0\2\33\1\34\5\0\1\33\2\0\15\33\1\215"+
    "\10\33\7\0\1\11\6\0\1\11\2\0\4\11\1\216"+
    "\21\11\7\0\1\11\6\0\1\11\2\0\3\11\1\217"+
    "\22\11\7\0\1\11\6\0\1\11\2\0\4\11\1\220"+
    "\21\11\7\0\1\11\6\0\1\11\2\0\15\11\1\221"+
    "\10\11\7\0\1\11\6\0\1\11\2\0\20\11\1\222"+
    "\5\11\7\0\1\11\6\0\1\11\2\0\14\11\1\223"+
    "\11\11\7\0\1\11\6\0\1\11\2\0\4\11\1\224"+
    "\21\11\7\0\1\11\6\0\1\11\2\0\24\11\1\225"+
    "\1\11\3\0\2\33\1\0\2\33\1\226\5\0\1\33"+
    "\2\0\26\33\3\0\2\33\1\0\2\33\1\34\5\0"+
    "\1\33\2\0\24\33\1\227\1\33\7\0\1\11\6\0"+
    "\1\11\2\0\2\11\1\230\23\11\7\0\1\11\6\0"+
    "\1\11\2\0\13\11\1\231\12\11\7\0\1\11\6\0"+
    "\1\11\2\0\3\11\1\232\22\11\7\0\1\11\6\0"+
    "\1\11\2\0\6\11\1\233\17\11\3\0\2\33\1\0"+
    "\2\33\1\234\5\0\1\33\2\0\26\33\7\0\1\11"+
    "\6\0\1\11\2\0\10\11\1\235\15\11\7\0\1\11"+
    "\6\0\1\11\2\0\15\11\1\236\10\11\7\0\1\11"+
    "\6\0\1\11\2\0\13\11\1\237\12\11\7\0\1\11"+
    "\6\0\1\11\2\0\20\11\1\240\5\11\7\0\1\11"+
    "\6\0\1\11\2\0\20\11\1\241\5\11\7\0\1\11"+
    "\6\0\1\11\2\0\4\11\1\242\21\11\7\0\1\11"+
    "\6\0\1\11\2\0\2\11\1\243\23\11\7\0\1\11"+
    "\6\0\1\11\2\0\13\11\1\244\12\11\7\0\1\11"+
    "\6\0\1\11\2\0\4\11\1\245\21\11\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4875];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\1\11\1\1\2\11\1\1\2\11"+
    "\15\1\2\11\1\0\1\11\6\0\25\1\10\0\1\1"+
    "\1\0\31\1\4\0\1\11\27\1\2\0\1\11\1\0"+
    "\20\1\1\11\2\0\10\1\1\11\1\0\4\1\1\11"+
    "\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[165];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  TraductorTokens(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 43: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 44: break;
          case 3:
            { System.out.println("COMA => " + yytext());
            }
            // fall through
          case 45: break;
          case 4:
            { System.out.println("PUNTO_Y_COMA => " + yytext());
            }
            // fall through
          case 46: break;
          case 5:
            { System.out.println("IGUAL => " + yytext());
            }
            // fall through
          case 47: break;
          case 6:
            { System.out.println("IDENTIFICADOR => " + yytext());
            }
            // fall through
          case 48: break;
          case 7:
            { System.out.println("CORCHETE_A => " + yytext());
            }
            // fall through
          case 49: break;
          case 8:
            { System.out.println("CORCHETE_C => " + yytext());
            }
            // fall through
          case 50: break;
          case 9:
            { System.out.println("LLAVE_A => " + yytext());
            }
            // fall through
          case 51: break;
          case 10:
            { System.out.println("LLAVE_C => " + yytext());
            }
            // fall through
          case 52: break;
          case 11:
            { System.out.println("ETIQUETA_VALOR => " + yytext());
            }
            // fall through
          case 53: break;
          case 12:
            { System.out.println("COMENTARIO// => " + yytext());
            }
            // fall through
          case 54: break;
          case 13:
            { System.out.println("DIRECCION => " + yytext());
            }
            // fall through
          case 55: break;
          case 14:
            { System.out.println("FONTCOLOR_ROJO => " + yytext());
            }
            // fall through
          case 56: break;
          case 15:
            { System.out.println("COMENTARIO/* => " + yytext());
            }
            // fall through
          case 57: break;
          case 16:
            { System.out.println("DIR_BACK => " + yytext());
            }
            // fall through
          case 58: break;
          case 17:
            { System.out.println("FONTCOLOR_AZUL => " + yytext());
            }
            // fall through
          case 59: break;
          case 18:
            { System.out.println("FUENTE_BOLD => " + yytext());
            }
            // fall through
          case 60: break;
          case 19:
            { System.out.println("DIR_BOTH => " + yytext());
            }
            // fall through
          case 61: break;
          case 20:
            { System.out.println("ARISTA => " + yytext());
            }
            // fall through
          case 62: break;
          case 21:
            { System.out.println("NODO => " + yytext());
            }
            // fall through
          case 63: break;
          case 22:
            { System.out.println("DIR_NONE => " + yytext());
            }
            // fall through
          case 64: break;
          case 23:
            { System.out.println("COLOR_ROJO => " + yytext());
            }
            // fall through
          case 65: break;
          case 24:
            { System.out.println("ARBOL => " + yytext());
            }
            // fall through
          case 66: break;
          case 25:
            { System.out.println("COLOR => " + yytext());
            }
            // fall through
          case 67: break;
          case 26:
            { System.out.println("FONTCOLOR_VERDE => " + yytext());
            }
            // fall through
          case 68: break;
          case 27:
            { System.out.println("HIJOS => " + yytext());
            }
            // fall through
          case 69: break;
          case 28:
            { System.out.println("ETIQUETA => " + yytext());
            }
            // fall through
          case 70: break;
          case 29:
            { System.out.println("SH => " + yytext());
            }
            // fall through
          case 71: break;
          case 30:
            { System.out.println("FUENTE_SOLID => " + yytext());
            }
            // fall through
          case 72: break;
          case 31:
            { System.out.println("FUENTE => " + yytext());
            }
            // fall through
          case 73: break;
          case 32:
            { System.out.println("COLOR_AZUL => " + yytext());
            }
            // fall through
          case 74: break;
          case 33:
            { System.out.println("SH_CIRCULO => " + yytext());
            }
            // fall through
          case 75: break;
          case 34:
            { System.out.println("FUENTE_DASHED => " + yytext());
            }
            // fall through
          case 76: break;
          case 35:
            { System.out.println("SH_CUADRADO => " + yytext());
            }
            // fall through
          case 77: break;
          case 36:
            { System.out.println("FONTCOLOR_AMARILLLO => " + yytext());
            }
            // fall through
          case 78: break;
          case 37:
            { System.out.println("COLOR_VERDE => " + yytext());
            }
            // fall through
          case 79: break;
          case 38:
            { System.out.println("DIR_FORWARD => " + yytext());
            }
            // fall through
          case 80: break;
          case 39:
            { System.out.println("COLOR_AMARILLLO => " + yytext());
            }
            // fall through
          case 81: break;
          case 40:
            { System.out.println("COLOR_FUENTE => " + yytext());
            }
            // fall through
          case 82: break;
          case 41:
            { System.out.println("SH_RECTANGULO => " + yytext());
            }
            // fall through
          case 83: break;
          case 42:
            { System.out.println("SH_DOBLECIRCULO => " + yytext());
            }
            // fall through
          case 84: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java TraductorTokens [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        TraductorTokens scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new TraductorTokens(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
